### ISSUE TITLE
Request for FailureStrategy example

### ISSUE THREAD

**Issue by kingo999** [VilledeMontreal/workit#130]
Can a concrete example of how to implement a Failure Strategy please be included?
Specifically how to deal with BPMN errors, for example:
await taskService.handleBpmnError(task, "BPMNError_Code", "Error message", variables);

thanks :-)

**Comment by kingo999** [comment]
Wow ! lightning speed.
Well done sir !

**Comment by OlivierAlbertini** [comment]
Thanks for reaching out! I made a PR in order to add this example. 
Notice that we are not compatible to Zeebe [0.22.1](https://github.com/creditsenseau/zeebe-client-node-js/blob/master/CHANGELOG.md#version-0221) yet. We will be soon!
This version brings the equivalent feature for `handleBpmnError `.

> You can now throw a BPMN Error in your process from a worker using the complete.error(errorCode: string, errorMessage?: string) method, or from the client using the ZBClient.throwError(throwErrorRequest: ThrowErrorRequest) method.

Actually, in the failureStrategy, you have a method:
`handle(error: any, message: IMessage<unknown, IWorkflowProps>, service: ICamundaService)`

You can do `service.ack(...)` or `service.nack(...)` but not something like `service.error(...)` (which will use `handleBpmnError ` for CamundaBPM and `complete.error(...)` for Zeebe).

If it's not already available, you can still do it for Camunda BPM. This is just a HTTP REST call and the [example provided](https://github.com/VilledeMontreal/workit/tree/master/examples/failure-strategy) show how to do it.

**Comment by OlivierAlbertini** [comment]
Also feel free to reopen the issue for further discussion.

**Comment by OlivierAlbertini** [comment]
Please, make sure you use the 4.0.3 version for the FailureStrategy example

**Comment by kingo999** [comment]
will do
